### ISSUE TITLE
can't delete images from items

### ISSUE THREAD

**Issue by commonplace** [aaroneiche/do-want#112] opened 2015-11-20 02:45 UTC
I added two images to one of my items. The first one I added is incorrect and unwanted. So, I edit the item, go to Manage Images, and hit the "x" on the first picture. It disappears. I hit Back and then Save Changes. But the image is still there. I can't get it to actually, really delete an image.

**Comment by aaroneiche** [comment] 2015-11-20 19:57
Confirmed.

**Comment by aaroneiche** [comment] 2015-11-20 21:28
Okay - it looks like this is an odd combination of images being uploaded, but not added to an item (which doesn't happen until save) so it doesn't have an itemid, so the system doesn't know which id to disassociate from the item. It's a totally reasonable possibility that I didn't anticipate. 

I'll get on it.

**Comment by aaroneiche** [comment] 2015-11-20 22:49
Found some problems on the backend too.

**Comment by aaroneiche** [comment] 2015-11-23 08:18
Fixed in merge #115

**Closed by aaroneiche** 2015-11-23 08:18 UTC
Labels: bug
